#version: '3.8'

services:
  mongo-demo:
    image: mongo:latest
    container_name: mongo-demo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=admin
    ports:
      - "127.0.0.1:27018:27017"
    networks:
      - mangui_mangui

  mangui-backend-demo:
    image: mangui/backend:latest
    container_name: mangui-backend-demo
    depends_on:
      - mongo-demo
    environment:
      - VIRTUAL_HOST=${MANGUI_VHOST}
      - VIRTUAL_PORT=8080
      - VIRTUAL_DEST=/
      - VIRTUAL_PATH=/api/
      - MANGUI_MAX_FILE_SIZE=50MB
      - MANGUI_AVAILABLE_HOSTS=${MANGUI_HOSTS}
      - MANGUI_JWT_SECRET=${MANGUI_JWT_SECRET_VALUE}
    networks:
      - mangui_mangui
    restart: always

  mangui-frontend-demo:
    image: mangui/frontend:latest
    container_name: mangui-frontend-demo
    depends_on:
      - mangui-backend-demo
    ports:
      - "3000"
    environment:
      - LETSENCRYPT_HOST=${MANGUI_VHOST}
      - VIRTUAL_HOST=${MANGUI_VHOST}
      - VIRTUAL_PORT=3000
      - VIRTUAL_PATH=/
    networks:
      - mangui_mangui
    restart: always

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  mangui_mangui:
    external: true
