#version: '3.8'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/conf:/etc/nginx/conf.d
      - ${PWD}/vhost:/etc/nginx/vhost.d:rw
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DHPARAM_SKIP=true
    networks:
      - mangui_mangui
    restart: always

  lets-encrypt:
    image: nginxproxy/acme-companion
    container_name: lets-encrypt
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=${LETS_ENCRYPT_MAIL}
    depends_on:
      - nginx-proxy
    networks:
      - mangui_mangui
    restart: always

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  mangui_mangui:
    external: true
