services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=admin
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - mangui

  mangui-backend:
    image: mangui-backend:latest
    container_name: mangui-backend
    depends_on:
      - mongo
    environment:
      - VIRTUAL_HOST=${MANGUI_VHOST}
      - VIRTUAL_PORT=8080
      - VIRTUAL_DEST=/api
      - VIRTUAL_PATH=/api
      - MANGUI_MAX_FILE_SIZE=50MB
      - MANGUI_AVAILABLE_HOSTS=${MANGUI_HOSTS}
      - MANGUI_JWT_SECRET=${MANGUI_JWT_SECRET_VALUE}
    networks:
      - mangui
    restart: always

  mangui-frontend:
    image: mangui-frontend:latest
    container_name: mangui-frontend
    depends_on:
      - mangui-backend
    ports:
      - "3000"
    environment:
      - VIRTUAL_HOST=${MANGUI_VHOST}
      - VIRTUAL_PORT=3000
      - VIRTUAL_PATH=/
    networks:
      - mangui
    restart: always

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/conf:/etc/nginx/conf.d
      - ${PWD}/vhost:/etc/nginx/vhost.d:rw
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - mangui-backend
      - mangui-frontend
    networks:
      - mangui
    restart: always

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  mangui: